-- Migration number: 0006 	 2024-08-20T19:36:27.745Z
INSERT INTO themes (title, created_at, updated_at) VALUES
  ('Católico', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Batista', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Metodista', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Presbiteriano', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Pentecostal', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Comunidades', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Evangélico', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Mulheres', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Homens', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Jovens', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Casais', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Famílias', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Idosos', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Crianças / Kids / Infantil', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Adolescentes / Teens', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Liderança', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Evangelização', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Adoração', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Cura e Libertação', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Finanças', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Educação Teológica', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Louvor', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Dança', strftime('%s', 'now'), strftime('%s', 'now')),
  ('Oração', strftime('%s', 'now'), strftime('%s', 'now'));
